import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="js csstransitions">
      <head>
<meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
<meta name="keywords" content="" />
<meta name="author" content="" />
<meta name="robots" content="" />
<meta name="description" content="" />
<meta name="format-detection" content="telephone=no"/>
<link rel="icon" href="images/favicon.ico" type="image/x-icon" />
<title>CarZone - Car Dealer Automotive Responsive HTML5 Template</title>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
        <script src="js/html5shiv.min.js"></script>
        <script src="js/respond.min.js"></script>
<link rel="stylesheet" type="text/css" href="css/plugins.css"/>
<link rel="stylesheet" type="text/css" href="css/style.min.css"/>
<link rel="stylesheet" type="text/css" href="css/templete.min.css"/>
<link rel="stylesheet" type="text/css" href="css/magnific-popup.css"/>
<link rel="stylesheet" type="text/css" href="css/skin/skin-1.css"/>
<link rel="stylesheet" type="text/css" href="css/custom.css"/>

<link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900|Open+Sans:300,400,600,700,800|Raleway:100,200,300,400,500,600,700,800,900|Poppins:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet"/>

</head>
      <body>
        
      <header className="site-header header-transparent style-1">
        <div className="sticky-header main-bar-wraper">
            <div className="main-bar clearfix ">
                <div className="container clearfix">
                    <div className="logo-header mostion">
						<a href="index.html"><img src="images/logo-light.png" className="logo" alt=""/></a>
					</div>
                    <button data-target=".header-nav" data-toggle="collapse" type="button" className="navbar-toggle collapsed" aria-expanded="false" > 
						<i className="fa fa-bars"></i>
					</button>
                    <div className="extra-nav">
                        <div className="extra-cell">
							<button title="READ MORE" rel="bookmark" data-toggle="modal" data-target="#car-details" className="site-button-link"><i className="fa fa-unlock-alt"></i><span className="extra-nav-text">login</span></button>
                            <button id="quik-search-btn" type="button" className="site-button-link"><i className="fa fa-search"></i><span className="extra-nav-text">Search</span></button>
                        </div>
                    </div>
                    <div className="dlab-quik-search bg-primary ">
                        <form action="#">
                            <input name="search" type="text" className="form-control" placeholder="Type to search"/>
                            <span id="quik-search-remove"><i className="fa fa-close"></i></span>
                        </form>
                    </div>
                    <div className="header-nav navbar-collapse collapse">	
						<ul className="nav navbar-nav">
							<li className="active"><a href="#">Home
                {/* <i className="fa fa-chevron-down"></i> */}
                </a>
								{/* <ul className="sub-menu">
									<li><a href="index.html">Home 1</a></li>
									<li><a href="index-2.html">Home 2</a></li>
									<li><a href="index-3.html">Home 3</a></li>
									<li><a href="car-shop/index.html">Car Shop</a></li>
									<li><a href="car-blog/index.html">Car Blog</a></li>
									<li><a href="shortcode/index.html">Car Shortcode</a></li>
								</ul> */}
							</li>
							{/* <li><a href="javascript:;">New<i className="fa fa-chevron-down"></i></a>
								<ul className="sub-menu">
									<li> <a href="javascript:;">Search Cars <i className="fa fa-angle-right"></i></a>
										<ul className="sub-menu">
											<li><a href="new-car-search.html">Search Car</a></li>
											<li><a href="new-car-search-result-list.html">Search Result List</a></li>
											<li><a href="new-car-search-result-column.html">Search Result Column</a></li>
										</ul>
									</li>
									<li><a href="new-car-latest.html">Latest Cars</a></li>
									<li><a href="new-car-popular.html">Popular Cars</a></li>
									<li><a href="new-car-upcoming.html">Upcoming Cars</a></li>
									<li> <a href="javascript:;">Dealers & Service Centers <i className="fa fa-angle-right"></i></a>
										<ul className="sub-menu">
											<li><a href="car-dealers.html">Car Dealers</a></li>
											<li><a href="car-service-center.html">Service Center</a></li>
										</ul>
									</li>
									<li><a href="on-road-price.html">On Road Price</a></li>
								</ul>
							</li> */}
							<li><a href="javascript:;">Used
                {/* <i className="fa fa-chevron-down"></i> */}
                </a>
								{/* <ul className="sub-menu">
									<li> <a href="javascript:;">In My City <i className="fa fa-angle-right"></i></a>
										<ul className="sub-menu">
											<li><a href="used-car-search-result.html">New York City</a></li>
											<li><a href="used-car-search-result.html">Chicago</a></li>
											<li><a href="used-car-search-result.html">Los Angeles</a></li>
											<li><a href="used-car-search-result.html">Boston</a></li>
											<li><a href="used-car-search-result.html">San Francisco</a></li>
											<li><a href="used-car-search-result.html">Washington</a></li>
											<li><a href="used-car-search-result.html">Seattle</a></li>
											<li><a href="used-car-search-result.html">Philadelphia</a></li>
											<li><a href="used-car-search-result.html">Austin</a></li>
											<li><a href="used-car-search-result.html">Detroit</a></li>
										</ul>
									</li>
									<li><a href="javascript:;">Search Car <i className="fa fa-angle-right"></i></a>
										<ul className="sub-menu">
											<li><a href="used-car-search.html">Search Car</a></li>
											<li><a href="used-car-search-result.html">Search Car Result</a></li>
											<li><a href="used-car-details.html">Used Car Detail</a></li>
										</ul>
									
									</li>
									<li><a href="used-car-details.html">Used Car Detail</a></li>
									<li><a href="used-car-sell.html">Sell Your Car</a></li>
									<li><a href="used-car-valuation.html">Car Valuation</a></li>
									
								</ul> */}
							</li>
							<li><a href="javascript:;">Compare
                {/* <i className="fa fa-chevron-down"></i> */}
                </a>
								{/* <ul className="sub-menu">
									<li><a href="compare-car.html">Compare Car</a></li>
									<li><a href="compare-car-result.html">Compare Car Result</a></li>
									<li><a href="write-review.html">Write Review</a></li>
									<li><a href="car-review.html">Car Review</a></li>
								</ul> */}
							</li>
							<li><a href="/car-details">Car Detail
                {/* <i className="fa fa-chevron-down"></i> */}
                </a>
								{/* <ul className="sub-menu">
									<li><a href="car-details-overview.html">Car Detail</a></li>
									<li><a href="car-detail-specifications.html">Car Specifications</a></li>
									<li><a href="car-detail-price.html">Car Price</a></li>
									<li><a href="car-detail-compare.html">Car Compare</a></li>
									<li><a href="car-detail-pictures.html">Car Pictures</a></li>
								</ul> */}
							</li>
							{/* <li className="has-mega-menu "> <a href="javascript:;">Pages<i className="fa fa-chevron-down"></i></a>
								<ul className="mega-menu">
									<li> <a href="javascript:;">Page</a>
										<ul>
											<li><a href="page-about.html">About Us</a></li>
											<li><a href="page-career.html">Career</a></li>
											<li><a href="page-services.html">Services</a></li>
											<li><a href="page-privacy-policy.html">Privacy Policy</a></li>
										</ul>
									</li>
									<li> <a href="javascript:;">Page</a>
										<ul>
											<li><a href="page-help.html">Help</a></li>
											<li><a href="page-faq.html">Faq's</a></li>
											<li><a href="page-error-404.html">404 Page</a></li>
											<li><a href="page-contact.html">Contact 1</a></li>
										</ul>
									</li>
									<li> <a href="javascript:;">Blog Page</a>
										<ul>
											<li><a href="blog-grid-2.html">Grid 2</a></li>
											<li><a href="blog-grid-2-sidebar.html">Grid 2 sidebar</a></li>
											<li><a href="blog-grid-3.html">Grid 3</a></li>
											<li><a href="blog-grid-3-sidebar.html">Grid 3 sidebar</a></li>
										</ul>
									</li>
									<li> <a href="javascript:;">Blog Page</a>
										<ul>
											<li><a href="blog-single.html">Single</a></li>
											<li><a href="blog-single-sidebar.html">Single sidebar</a></li>
											<li><a href="blog-half-img-sidebar.html">Half image sidebar</a></li>
											<li><a href="blog-large-img-sidebar.html">Large image sidebar</a></li>
										</ul>
									</li>
								</ul>
							</li> */}
						</ul>
					</div>
                </div>
            </div>
        </div>
    </header>
        {children}
        <script  src="js/jquery.min.js"></script>
<script src="js/wow.js"></script>
<script  src="js/bootstrap.min.js"></script>
<script  src="js/bootstrap-select.min.js"></script>
<script  src="js/jquery.bootstrap-touchspin.js"></script>
<script  src="js/magnific-popup.js"></script>
<script  src="js/waypoints-min.js"></script>
<script  src="js/counterup.min.js"></script>
<script src="js/imagesloaded.js"></script>
<script src="js/masonry-3.1.4.js"></script>
<script src="js/masonry.filter.js"></script>
<script  src="js/owl.carousel.js"></script>
<script  src="js/owl.linked.js"></script>
<script  src="js/dz.carousel.js"></script>
<script  src="js/dz.ajax.js"></script>

<script src="js/modernizr.custom.js"></script>
<script src="js/jquery.hoverdir.js"></script>
<script  src="js/custom.js"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBjirg3UoMD5oUiFuZt3P9sErZD-2Rxc68&callback=initMap"></script>

      </body>
    </html>
  );
}
